a = input('Digite algo: ')
print('O tipo primitov desta informação é: ',type(a))
print('Só tem espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('É completamente maiúscula?', a.isupper())
print('É completamente minúscula?', a.islower())
print('É capitalizada?', a.istitle())
